name: Build and deploy
on:
  push:
    branches:
      - master

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: CheackOut Repo
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: "10.x"
  
      - name: Install Dependencies
        run: npm install

      - name: Building the site
        run: npm run build
      
      - name: deploy to firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: AIzaSyAc5mdOC-FCdOsP1jB6ptKI3w4i6xw6hdc

